-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, sum(os.SALES_AMOUNT) * p.PRICE as SALES
FROM PRODUCT as p
INNER JOIN OFFLINE_SALE as os
on p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY os.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;