-- 코드를 입력하세요
SELECT ub.WRITER_ID AS USER_ID,uu.NICKNAME,SUM(ub.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS ub
INNER JOIN USED_GOODS_USER AS uu
ON ub.WRITER_ID = uu.USER_ID
WHERE ub.STATUS = "DONE"
GROUP BY ub.WRITER_ID,uu.NICKNAME
HAVING sum(ub.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;